### PR TITLE
fix person project section

### LINKED ISSUE #542: Bring back "projects" on individual person pages
They are now missing, but were added in #333 . They need to be restored.

### PR DESCRIPTION
**Pull request by spencercheng**
closes #542

### CODE REVIEW

File: single-person.php [hunk 1]
```diff
@@ -113,23 +113,25 @@
 							$id = $mypod -> field('id');
 							$permalink = get_permalink($id);
 							$personnel = $mypod -> field('project_personnel.ID');
+							$Live = "Live";
```
Comment (WorldsEndless) [inline single-person.php:116]: rather than calling them simply things like`$Live`, please prefix them to something that distinguishes them as something unique to our project. such as `$ODHProjectStatus_Live`. WordPress has never  done proper namespacing (although PHP added it since then), so let's follow the WordPress idiom of prefixing our variables. This is particularly important since these will be used in multiple places.

**Review by WorldsEndless — CHANGES_REQUESTED** [review]

**Review by WorldsEndless — APPROVED** [review]
